# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-14 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_category_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
